name: CI/CD Pipeline - Deploy to Netlify

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Lint
        run: npm run lint

      - name: Run Tests
        run: npm test

      - name: Build Project
        run: npm run build

  unusedexports:
    name: Find unused exports (dead code)
    runs-on: ubuntu-latest
    needs: install
    environment:
      name: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Restore node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{runner.os}}-${{hashFiles('**/yarn.lock')}}
      - name: Run ts-prune
        run: yarn find-dead-code

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: './dist' # ou './build', depende do seu projeto
          production-branch: master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
